food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    path('',views.IndexClassView.as_view(),name='index'),
    path('<int:pk>/',views.FoodDetail.as_view(),name = "detail"),
    path('item/',views.item,name='item'),
    #add items
    path('add/',views.CreateItem.as_view(),name="create_item"),
    #update items
    path('update/<int:id>/',views.update_item,name='update_item'),
    path('delete/<int:id>/',views.delete_item,name='delete_item'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name = 'users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name = 'users/logout.html'),name='logout'),
    path('profile/',user_views.profile_page,name='profile'),
]



urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from  django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Item(models.Model):
    user_name = models.ForeignKey(User, on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default="https://www.thefuzzyduck.co.uk/wp-content/uploads/2024/05/image-coming-soon-placeholder-01-660x660.png")


    def __str__(self):
        return self.item_name
    
    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})
    

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default="profile.png",upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']
        

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

food/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from . models import Item
from . forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
# Create your views here.

# def index(request):
#     item_list = Item.objects.all()
#     context ={
#         "item_list" : item_list,
#     }
#     return render(request,"food/index.html",context)

class IndexClassView(ListView):
    model = Item
    template_name = "food/index.html"
    context_object_name = 'item_list'


def item(request):
    return HttpResponse("This is item")

# def detail(request,item_id):
#     item_detail = Item.objects.get(pk = item_id)
#     context = {
#         "item" : item_detail,
#     }
#     return render(request,"food/detail.html",context)

class FoodDetail(DetailView):
    model = Item
    template_name = "food/detail.html"

# def create_item(request):
#     form = ItemForm(request.POST or None)
    
#     if form.is_valid():
#         form.save()
#         return redirect('food:index')
    
#     return render(request,"food/item-form.html",{'form':form})

class CreateItem(CreateView):
    model = Item
    fields = ['item_name','item_desc','item_price','item_image']
    template_name = "food/item-form.html"

    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)
    
    

def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None,instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request,'food/item-form.html',{'form':form,'item':item})

def delete_item(request,id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    return render(request,'food/item-delete.html',{'item':item})

users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f"Welcome {username}, your account is created")
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request,'users/register.html',{'form':form})

@login_required
def profile_page(request):
    return render(request,'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <title>Document</title>
</head>
<body>

    <nav class="navbar navbar-dark bg-dark ">
        <a href="#" class="navbar-brand">FoodApp</a>
    
        <ul class="nav justify-content-end">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'food:create_item' %}">Add Item</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Add Item</a>
            </li>
          {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="#">Delete Item</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">View Item</a>
            </li>
            {% if user.is_authenticated %}
            <form method="post" action="{% url 'logout' %}">
              {% csrf_token %}
               <li class="nav-item">
                <button class="nav-link" type="submit">Logout</button>
                </li>
            </form>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'profile'%}">Profile</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>

            {% endif %}

        
            <li class="nav-item">
              <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </li>
          </ul>
    </nav>

    {% if messages%}
      {% for message in messages %}
      <div class = "alert alert-{{message.tags}}">
        {{message}}
      </div>
      {% endfor %}
    {% endif %}

    {% block body %}

    {% endblock %}
    
</body>
</html>

food/templates/food/detail.html
{% extends "food/base.html" %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6 mt-2">
            <img height="400px" width="400px" src="{{item.item_image}}" class="card">
        </div>
        <div class="col-md-6 mt-2">
            <h1>{{ object.item_name }}</h1>
            <h2>{{ object.item_desc }}</h2>
            <h3>$ {{ object.item_price }}</h3>

            {% if request.user == item.user_name %}
            <a href="{% url 'food:delete_item' item.id %}">Delete</a>
            {% endif %}
            
        </div>
    </div>
</div>


{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Document</title>

</head>
<body>

{% block body %}

{% for item in item_list %}
    <div class="row">
        <div class="col-md-3 offset-md-2 mt-2">
            <img class="card" height="150px" width="150px" src="{{item.item_image}}" alt="">
        </div>
        <div class="col-md-4 mt-2">
            <h3>{{item.item_name}}</h3>
            <h5>{{item.item_desc}}</h5>
            <h6>$ {{item.item_price}}</h6>
            <h6>{{item.user_name}}</h6>
        </div>
        <div class="col-md-2 mt-2">
            <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
        </div>
    </div>
{% endfor %}


{% endblock %}



</body>
</html>

food/templates/food/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }}</h2>
    <button type="submit">Confirm</button>
</form>

food/templates/food/item-form.html
{% extends "food/base.html" %}

{% block body %}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-dark bg-white">
                    <div class="card-title offset-md-4">
                        <h3>Add Item</h3>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}

                          <!-- Display non-field errors -->
                          {% if form.non_field_errors %}
                          <div class="alert alert-danger">
                              {% for error in form.non_field_errors %}
                                  <p>{{ error }}</p>
                              {% endfor %}
                          </div>
                          {% endif %}

                        {% for field in form %}

                        <div class="mb-3">
                            <label for="id_{{field.name}}" class="form-label">{{field.name.capitalize}}</label>
                            <div class="form-control-plaintext form-control-lg d-grid gap-2">{{field}}</div>
                          </div>

                           <!-- Display field-specific errors -->
                           {% if field.errors %}
                           <div class="text-danger">
                               {% for error in field.errors %}
                                   <p>{{ error }}</p>
                               {% endfor %}
                           </div>
                           {% endif %}
                         
                        {% endfor %}

                        <div class="d-grid gap-2">
                            <button class="btn btn-success mt-3" type="submit">Save</button>
                        </div>
                        
                       
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock%}

users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-dark bg-white">
                    <div class="card-title offset-md-4">
                        <h3>Login</h3>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}

                          <!-- Display non-field errors -->
                          {% if form.non_field_errors %}
                          <div class="alert alert-danger">
                              {% for error in form.non_field_errors %}
                                  <p>{{ error }}</p>
                              {% endfor %}
                          </div>
                          {% endif %}

                        {% for field in form %}

                        <div class="mb-3">
                            <label for="id_{{field.name}}" class="form-label">{{field.name.capitalize}}</label>
                            <div class="form-control-plaintext form-control-lg d-grid gap-2">{{field}}</div>
                          </div>

                           <!-- Display field-specific errors -->
                           {% if field.errors %}
                           <div class="text-danger">
                               {% for error in field.errors %}
                                   <p>{{ error }}</p>
                               {% endfor %}
                           </div>
                           {% endif %}
                         
                        {% endfor %}

                        <div class="d-grid gap-2">
                            <button class="btn btn-primary mt-3" type="submit">Login</button>
                        </div>
                        
                       
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/logout.html
<h1>Successful logout</h1>

users/templates/users/profile.html
<h1>{{user.username}}</h1>

<img height="100px" width="100px" src="{{ user.profile.image.url }}" alt="">

users/templates/users/register.html
{% extends 'food/base.html'%} {% block body %}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-dark bg-white">
                    <div class="card-title offset-md-4">
                        <h3>Register</h3>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %} 

                         <!-- Display non-field errors -->
                         {% if form.non_field_errors %}
                         <div class="alert alert-danger">
                             {% for error in form.non_field_errors %}
                                 <p>{{ error }}</p>
                             {% endfor %}
                         </div>
                         {% endif %}
                        
                        {% for field in form %}

                        <div class="mb-3">
                            <label for="id_{{field.name}}" class="form-label">{{field.name.capitalize}}</label>
                            <div class="form-control-plaintext form-control-lg d-grid gap-2">{{field}}</div>
                          </div>

                           <!-- Display field-specific errors -->
                           {% if field.errors %}
                           <div class="text-danger">
                               {% for error in field.errors %}
                                   <p>{{ error }}</p>
                               {% endfor %}
                           </div>
                           {% endif %}

                        {% endfor %}

                        <div class="d-grid gap-2">
                        <button class="btn btn-primary mt-3 mb-3" type="submit">Register</button>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}